- readme.md
Hi,
this PR updates the README.MD with installation description. :)
Best regards,
Jacob
> Add install description

- index.js
This helper enables the `useEslintRc` option in ESLint
> feat: add useEslintRc helper

- index.js
- readme.md
* This helper modifies the ESLint loader to process .ts and .tsx files as well.
> feat: Add enableEslintTypescript helper.

- index.js
- readme.md
Less configuration could be a little bit complex since there're some differences between `development` mode and `production` mode.
I've tested it could work in simple scenarios. I hope someone can give feedbacks about their use cases such as [antd](https://ant.design/) or else.
> feat: Enable less-loader in cra

- package-lock.json
- package.json
This will populate a link on npm so the github repo is easier to discover.
> Add repository field to package.json

- index.js
Function to disable chunk or code splitting, see: https://github.com/facebook/create-react-app/issues/5306 for more info
> Add `disableChunk`

- index.js
See https://github.com/timarney/react-app-rewired/pull/107
> Allow .eslintignore files to be used

- index.js
- readme.md
this PR adds the ability to inject an object to webpack's resolve section
> add function to add webpack resolve and updates readme accordingly

- index.js
- readme.md
>  update readme.md about addLessLoader

- index.js
- readme.md
Reverts arackaf/customize-cra#69
> Revert "addWorkerLoader"

- readme.md
Update(README.md): TypeScript with Less  …
CRA create TypeScript project, not find `.module.less` module.
>  Update(README.md): TypeScript with Less

- index.js
Oops. 😰 
https://github.com/arackaf/customize-cra/pull/84
> chore: fix typo in addWebpackExternals

- .prettierrc
- index.js
This PR adds a `prettier` configuration that nearly matches the project's original style. `index.js` has been formatted with this configuration.
> chore: add .prettierrc

- contributing.md
- readme.md
closes #128 
This PR creates a barebones `contributing.md` file and a note about its existence in `readme.md`.
> doc: create contributing.md

- api.md
- src/customizers/__snapshots__/webpack.test.js.snap
- src/customizers/webpack.js
- src/customizers/webpack.test.js
Re-opening [this PR](https://github.com/arackaf/customize-cra/pull/132) by @breeze2 because I made a noob git mistake. Sorry @breeze2!
> Sometimes you may want to use a combination of the function, regex, object ... webpack.js.org/configuration/externals/#combining-syntaxes
> feat: addWebpackExternals with combining syntaxes

- .all-contributorsrc
- contributing.md
- package-lock.json
- package.json
- readme.md
closes #115 
This PR adds `all-contributors` to the project, and adds a few users (@dqu, @breeze2, @Terryand) that have contributed since I started contributing.
> chore: add all-contributors

- api.md
- src/utilities.js
> docs(api): add getBabelLoader

- src/customizers/babel.js
- src/customizers/webpack.js
fixes #120 
BREAKING CHANGE: config is now duplicated for each function rather than
modifying the input config
> refactor(customizers): make pure fns

- .all-contributorsrc
- api.md
- readme.md
- src/customizers/__snapshots__/webpack.test.js.snap
- src/customizers/webpack.js
- src/customizers/webpack.test.js
As per: https://webpack.js.org/configuration/target/
This can be useful for things like Electron apps. I've tested this with one of my own apps and it seems to work as expected.
> feat: implement setWebpackTarget

- .all-contributorsrc
- readme.md
- src/customizers/__snapshots__/webpack.test.js.snap
- src/customizers/webpack.js
- src/customizers/webpack.test.js
> solve #153

- .all-contributorsrc
- readme.md
- src/customizers/__snapshots__/webpack.test.js.snap
- src/customizers/webpack.js
- src/customizers/webpack.test.js
> feat: add setWebpackPublicPath

- .all-contributorsrc
- readme.md
- src/customizers/__snapshots__/webpack.test.js.snap
- src/customizers/webpack.js
- src/customizers/webpack.test.js
fix the [issue#168](https://github.com/arackaf/customize-cra/issues/168)
> feat: add http/https cases to setWebpackPublicPath

- api.md
- src/customizers/__snapshots__/webpack.test.js.snap
- src/customizers/webpack.js
- src/customizers/webpack.test.js
This method is necessary for optimizing react app. Please check and merge it
> feat: add new method to customize optimization.splitChunks

- .all-contributorsrc
- .prettierrc
- api.md
- readme.md
- src/customizers/__snapshots__/webpack.test.js.snap
- src/customizers/webpack.js
- src/customizers/webpack.test.js
closes https://github.com/arackaf/customize-cra/issues/67
Can't seem to make `create-react-app` respect this config reliably. Nevertheless, it's now an option.
> feat: add setWebpackStats

- api.md
- src/customizers/__snapshots__/webpack.test.js.snap
- src/customizers/webpack.js
- src/customizers/webpack.test.js
> feat: add adjustStyleLoaders

- .all-contributorsrc
- api.md
- readme.md
- src/customizers/__snapshots__/babel.test.js.snap
- src/customizers/babel.js
- src/customizers/babel.test.js
Add remove internal babel plugin function.
> feat: add remove internal babel plugin function.

- .all-contributorsrc
- api.md
- readme.md
- src/customizers/webpack.js
fixes #134 
update addLessLoader, used css-loader ^3.0.0
> update: addLessLoader
